version: '3.5'

services:
  mobile-reality-app:
    build:
      context: .
    ports:
      - 3001:3000
    restart: always
    volumes:
      - ".:/var/www/app"
    working_dir: "/var/www/app"
    command: "npm run start:dev"
    networks: 
      - net_dev
    depends_on: 
      - redis
      - mysql-db
  redis:
    image: redis:5
    networks:
      - net_dev
  mysql-db:
        image: mysql:8.0.17
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        networks:
            - net_dev
networks:
  net_dev: